#include "file.h"

#include <cstdio>

#include "../HUD/hud.h"
#include "../gps/gps.h"
#include "../sdCard/sdCard.h"

// Initializations
char filename[] = "/00000000.bin";
char directory[] = "/00-00-00";
char fileDir[23];

Bounce inputButton = Bounce(BUTT_PIN, 5);
int lastPressed = 0;

// Function Definitions
void getFilename(uint8_t hour, uint8_t minute, uint8_t second) {
    // Only hour, minute and second are saved in UTC time
    // Please move files before start of new day
    sprintf(filename, "/%02d%02d%02d.bin", hour, minute, second);
}

void getDirectory(uint8_t day, uint8_t month, uint8_t year) {
    // Please move files before start of new day
    sprintf(directory, "/%02d-%02d-%02d", year, month, day);
}

/**
 * Creates the file at the path stored in fileDir
 */
void createFile() {
    Serial.println(fileDir);
    if (EN_FAST_SD) {
        bajaDataFast.open(fileDir, O_RDWR | O_CREAT | O_AT_END);  // Create file
        if (!bajaDataFast) {
            Serial.println("File failed to write");
            Serial.println(bajaDataFast.getError());
            USE_SD = false;
        }
        bajaDataFast.sync();
    } else {
        bajaData = SD.open(fileDir, FILE_WRITE);  // Create file
        if (bajaData == 0) {
            Serial.println("File failed to write");
            USE_SD = false;
        }
    }
}

/**
 * Creates a new file on the SD card with sequential filename 00000000,
 * 00000001, 00000002, etc.
 */
void createSequentialFile() {
    getDirectory(0, 0, 0);
    SD.mkdir(directory);
    // Find the next unused filename in the 0 0 0 directory.
    for (unsigned long i = 0; i < MAX_FILENAME; ++i) {
        snprintf(filename, sizeof(filename), "/%08lu.bin", i);
        strcpy(fileDir, directory);
        strcat(fileDir, filename);
        if (!SD.exists(fileDir)) {
            break;
        }
    }
    createFile();
}

/**
 * Creates a new file on the SD card with filename generated by getFilename and
 * getDirectory using datetime provided
 */
void createDateTimeFile(uint8_t day, uint8_t month, uint8_t year, uint8_t hour,
                        uint8_t minute, uint8_t second) {
    getFilename(hour, minute, second);
    getDirectory(day, month, year);
    SD.mkdir(directory);
    Serial.println(filename);
    Serial.println(directory);
    strcpy(fileDir, directory);
    strcat(fileDir, filename);
    createFile();
}

void handleInputButton() {
    inputButton.update();

    if (inputButton.fallingEdge()) {
        Serial.print("Button Pressed: ");

        if (gps_active) {
            HUD_SHOW =
                (HUD_SHOW + 1) % HUD_MODES;  // Cycle through the HUD modes
            Serial.print(" Mode = ");
            Serial.print(HUD_SHOW);
        } else {
            if (millis() - lastPressed < 250) {
                Serial.println("Start recording");
                strip.setPixelColor(2, strip.Color(100, 0, 100));
                EN_GPS = false;

                // We have no GPS, use a sequential filename
                createSequentialFile();

                // File header example
                // bajaData.println("Time, Absolute X, Absolute Y, Absolute Z,
                // Accel X, Accel Y, Accel Z, Gravity X, Gravity Y, Gravity Z,
                // Gyro X, Gyro Y, Gyro Z, IMU Temp, HasGPS, Latitude
                // (DDMM.MMMMM), Longitude (DDDMM.MMMMM)(will remove leading
                // zeros), Angle (North is 0 and CW)), Speed (knots), Date +
                // Time, Primary Temp i2c, Secondary Temp i2c, Suspension
                // Travel, Strain, FR_RPM, REAR_SPEED, Battery Percentage,
                // Battery Voltage");

                gps_flash = true;

                for (int i = 0; i < LED_COUNT; i++) {
                    strip.setPixelColor(i, strip.Color(0, 255, 0));
                }

                Serial.print("GPS cancelled");
                digitalWrite(STATUS_PIN, HIGH);
                strip.show();
                delay(1000);
                statusLED = true;
            }
            lastPressed = millis();
        }
        Serial.println();
    }
}